# compile markdown README to pdf for printing
language: generic
sudo: required
cache: packages

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y texlive texlive-lang-german  texlive-latex-recommended  texlive-latex-extra
  - sudo apt-get install pandoc

after_success:
  - mkdir ~/tmp && cd ~/tmp
  - git clone https://${GH_TOKEN}@github.com/khufkens/paper_writing_checklist.git .
  - pandoc -s -o paper_writing_advice.pdf README.md
  - git add *.pdf
  - git commit -am "[skip travis] update pdf (travis build ${TRAVIS_BUILD_NUMBER})"
  - git push -f origin master

env:
  global:
    secure: "R0DVu023ItWrm2mbohcGvebgHAFppwXYvde71Vym9rfaHw69AVcmNlQy3F57KMCSnxRdcq7aEAn9P40HiMDHY6LrPji00Vn01dIWA8boBuRrNdQOeUnCYTYFpxfWNz6itoZFYhcCWpAInlnX6rghUpgSGLeYP+N6qoyVJk6GuFQAOdUY/jNomMgcfoSKnUXPDl9gW/7ALQy1b+KstA746QDXN5ACkvv7qqSntmcnpaph9kUjVXdVvxhD6bXuRMcyXLXw1NW3Np7AwjDO2bJi9bgBwsE//dr8VIreXQdhF7c7OJJARvqhB5f6cpQpxqudXrzBFaPHDQBYWnv0j+pNnNHqg2Xv3b8k5Pvjt/v5+Y2XTf7Bs7OmwkB+usV4iedAEMxtlJwBrUOCaw4LcoYz4X2YGq/AuwOOYHRx6r4EHSpvh4L0JdB9JwotRkRMeNSCakhQ9OmKJKLdx43B31PmPn36C8RbZal5iFP/vb7aod8y5ww6Uv9rhaDguP5yH9wVkH3+2hauc8EdU9lAWHSqi/hGZvJM9UCINuUKzzgKoEPafhooVu3bsrvexkElbqyYNq4f3d057yYh5RQXWiHMljcK2SJfPeRHo1ilPeb8LoYlOcFGIHoEDfZiBQYOqRXm7XxunVih+hZJLIf30aq3RTAwLZ3OOCRn6Sj1iMfk+g8="